//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPClientSchoolApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnouncementTable> AnnouncementTables { get; set; }
        public virtual DbSet<AttendanceTable> AttendanceTables { get; set; }
        public virtual DbSet<FeeDueTable> FeeDueTables { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<MessageTable> MessageTables { get; set; }
        public virtual DbSet<NoticeTable> NoticeTables { get; set; }
        public virtual DbSet<ParentTable> ParentTables { get; set; }
        public virtual DbSet<PersonnelTable> PersonnelTables { get; set; }
        public virtual DbSet<RemarkTable> RemarkTables { get; set; }
        public virtual DbSet<ReminderTable> ReminderTables { get; set; }
        public virtual DbSet<SchoolSubjectSetting> SchoolSubjectSettings { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<AboutTable> AboutTables { get; set; }
        public virtual DbSet<AssignmentTable> AssignmentTables { get; set; }
        public virtual DbSet<ChildAchievementTable> ChildAchievementTables { get; set; }
    }
}
