//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPClientSchoolApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderTable
    {
        public int ReminderID { get; set; }
        public string EventTypeToken { get; set; }
        public string Detail { get; set; }
        public string MCD { get; set; }
    }
}
